export const HEAT_CONFIG = {
  HOT: {
    label: "HOT",
    sub: "3 C's",
    bg: "bg-emerald-100",
    text: "text-emerald-900",
    badgeBg: "bg-emerald-600",
    badgeText: "text-white",
    dot: "bg-emerald-600",
    countBg: "bg-emerald-600",
    countText: "text-white",
    filterBg: "bg-emerald-50",
    filterBorder: "border-emerald-600",
    filterText: "text-emerald-900",
  },
  WARM: {
    label: "WARM",
    sub: "2 to 1 C's",
    bg: "bg-green-100",
    text: "text-green-800",
    badgeBg: "bg-green-500",
    badgeText: "text-white",
    dot: "bg-green-500",
    countBg: "bg-green-500",
    countText: "text-white",
    filterBg: "bg-green-50",
    filterBorder: "border-green-500",
    filterText: "text-green-800",
  },
  COLD: {
    label: "COLD",
    sub: "1 to 0 C's",
    bg: "bg-green-50",
    text: "text-green-600",
    badgeBg: "bg-green-300",
    badgeText: "text-green-900",
    dot: "bg-green-400",
    countBg: "bg-green-300",
    countText: "text-green-900",
    filterBg: "bg-green-50/50",
    filterBorder: "border-green-300",
    filterText: "text-green-600",
  },
};

// export const HEAT_CONFIG = {
//   HOT: {
//     label: "HOT",
//     sub: "3 C's",
//     bg: "bg-red-100",
//     text: "text-red-900",
//     badgeBg: "bg-red-400",
//     badgeText: "text-red-900",
//     dot: "bg-red-500",
//     countBg: "bg-red-400",
//     countText: "text-red-900",
//     filterBg: "bg-red-50",
//     filterBorder: "border-red-400",
//     filterText: "text-red-900",
//   },
//   WARM: {
//     label: "WARM",
//     sub: "2 to 1 C's",
//     bg: "bg-yellow-100",
//     text: "text-yellow-900",
//     badgeBg: "bg-yellow-200",
//     badgeText: "text-yellow-900",
//     dot: "bg-orange-500",
//     countBg: "bg-yellow-200",
//     countText: "text-yellow-900",
//     filterBg: "bg-yellow-50",
//     filterBorder: "border-yellow-400",
//     filterText: "text-yellow-900",
//   },
//   COLD: {
//     label: "COLD",
//     sub: "1 to 0 C's",
//     bg: "bg-blue-100",
//     text: "text-blue-900",
//     badgeBg: "bg-blue-200",
//     badgeText: "text-blue-900",
//     dot: "bg-blue-500",
//     countBg: "bg-blue-200",
//     countText: "text-blue-900",
//     filterBg: "bg-blue-50",
//     filterBorder: "border-blue-400",
//     filterText: "text-blue-900",
//   },
// };

export const HEAT_ORDER = ["HOT", "WARM", "COLD"];
export const LEVEL_ORDER = ["HIGH", "MEDIUM", "LOW"];
export const PYRAMID_WIDTHS = { HIGH: "w-3/5", MEDIUM: "w-4/5", LOW: "w-full" };